version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../Employee/:/var/www/html/
    ports:
      - '9000:80'
    #restart: always
    depends_on:
      - mysql
    tty: true
    privileged: true

  mysql:
    container_name: mysql
    image: mysql:8.0.32
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --sql_mode=""
    ports:
      - '3307:3306'
    volumes:
      - ../sql:/usr/share/db
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
